name: "Continous Integration"
on:
  push:
    branches: [ "ops" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm ci
    - run: npm test
    - run: npm run build

  
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
       push: true
       tags: mohamedamineblibech/node:latest

    
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_ADDRESS }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/node_project/
          git pull origin main
          git status
          sudo docker-compose up --build -d
             
