name: Node.js CI

on:
  push:
    branches: [ "ops" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup Node.js using a specific version to avoid version conflicts
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
      
    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run your tests
    - name: Run tests
      run: npm test

    # Build your code
    - name: Build
      run: npm run build

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: mohamedamineblibech/node:latest

    # Deploy using SSH
    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_ADDRESS }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/node_project/
          git pull origin main
          git status
          sudo docker-compose up --build -d
